define(
   ({
    _widgetLabel: "Dessin",
    selectDrawMode: "Sélectionner le mode de dessin",
    clear: "Effacer",
    point: "Point",
    line: "Ligne",
    polyline: "Polyligne",
    freehandPolyline: "Polyligne à main levée",
    triangle: "Triangle",
    extent: "Enveloppe",
    circle: "Cercle",
    ellipse: "Ellipse",
    polygon: "Polygone",
    freehandPolygon: "Polygone à main levée",
    text: "Texte",
	textWarningMessage:"Le texte doit être saisi avant de placer le point sur la carte.",
    style: "Style",
    alpha: "Transparence",
    width: "Largeur",
    size: "Taille",
    color: "Couleur",
    markerColor: "Couleur du symbole ponctuel",
    outlineColor: "Couleur du contour",
    lineColor: "Couleur de ligne",
    fillColor: "Couleur de remplissage",
    showMeasurements: "Afficher les mesures",
    areaUnits: "Unités de surface",
    distanceUnits: "Unités de distance",
    kilometers: "Kilomètres",
    miles: "Miles",
    meters: "Mètres",
    feet: "Pieds",
    yards: "Yards",
    squareKilometers: "Kilomètres carrés",
    squareMiles: "Miles carrés",
    acres: "Acres",
    hectares: "Hectares",
    squareMeters: "Mètres carrés",
    squareFeet: "Pieds carrés",
    squareYards: "Yards carrés",
	confirmDrawDelete:"Ce dessin va être supprimé",
	all:"Tous",
	draws:'dessins',
	exportTitle:"Exporter les dessins",
	importTitle:"Importer des dessins",
	importErrorMessageNavigator:"Votre navigateur ne supporte pas cette fonctionnalité.",
	importErrorWarningSelectFile:"Merci de sélectionner un fichier.",
	importErrorFileStructure:"Impossible d'importer les dessins, la structure du fichier n'est pas bonne.",
	importWarningNoExport0Draw:"Pas d'export (aucun dessin à exporter).",
  })
);