define(
	({
		_widgetLabel : "Dessins avancés",
		yes:"Oui",
		no:"Non",
		selectDrawMode : "Sélectionner le mode de dessin",
		clear : "Effacer",
		point : "Point",
		line : "Ligne",
		polyline : "Polyligne",
		freehandPolyline : "Polyligne à main levée",
		triangle : "Triangle",
		extent : "Enveloppe",
		circle : "Cercle",
		ellipse : "Ellipse",
		polygon : "Polygone",
		freehandPolygon : "Polygone à main levée",
		text : "Texte",
		textWarningMessage : "Le texte doit être saisi avant de placer le point sur la carte.",
		style : "Style",
		alpha : "Transparence",
		width : "Largeur",
		size : "Taille",
		color : "Couleur",
		markerColor : "Couleur du symbole ponctuel",
		outlineColor : "Couleur du contour",
		lineColor : "Couleur de ligne",
		fillColor : "Couleur de remplissage",
		showMeasurements : "Afficher les mesures",
		areaUnits : "Unités de surface",
		distanceUnits : "Unités de distance",
		pointUnits : "Unités",
		unitMap : "Unités de la carte",
		unitDMS : "Degrés Minutes Secondes",
		unitDD : "Degrés décimaux",
		kilometers : "Kilomètres",
		miles : "Miles",
		meters : "Mètres",
		nauticals : "Milles marins",
		feet : "Pieds",
		yards : "Yards",
		squareKilometers : "Kilomètres carrés",
		squareMiles : "Miles carrés",
		acres : "Acres",
		hectares : "Hectares",
		squareMeters : "Mètres carrés",
		squareFeet : "Pieds carrés",
		squareYards : "Yards carrés",
		confirmDrawDelete : "Supprimer ce dessin ?",
		confirmDrawCheckedDelete : "Supprimer les dessins sélectionnés ?",
		all : "Tous",
		draws : 'dessins',
		addDrawTitle : 'Ajouter un dessin',
		editDrawTitle : 'Modifier un dessin',
		listDrawTitle : 'Liste des dessins',
		importExportTitle : 'Importer ou exporter les dessins',
		exportTitle : "Exporter les dessins",
		importTitle : "Importer des dessins",
		importErrorMessageNavigator : "Votre navigateur ne supporte pas cette fonctionnalité.",
		importErrorWarningSelectFile : "Merci de sélectionner un fichier.",
		importDragAndDropMessage : "Sélectionnez un fichier ou glissez/déplacez en un dans cette zone.",
		importWarningNoDrawings : "Pas de dessins à charger",
		importErrorFileStructure : "Impossible d'importer les dessins, la structure du fichier n'est pas bonne.",
		importWarningNoExport0Draw : "Pas d'export (aucun dessin à exporter).",
		importCloseButton:"Fermer",
		nameField : "Nom",
		symbolField : "Symbol",
		nameFieldDefaultValue : "Mon dessin",
		descriptionField : "Description",
		localLoading : "Vos derniers dessins ont été automatiquement chargés",
		editLabel : "Modifier ce dessin",
		deleteLabel : "Supprimer ce dessin",
		upLabel : "Monter ce dessin",
		downLabel : "Descendre ce dessin",
		zoomLabel : "Zoomer sur ce dessin",
		zoomAllLabel : "Zoomer sur les dessins sélectionnés",
		copyLabel : "Copier les dessins sélectionnés",
		copySuffix : " (copie)",
		deleteAllLabel : "Supprimer les dessins sélectionnés",
		exportLabel : "Exporter les dessins sélectionnés",
		noSelection : "Aucun dessin sélectionné",
		saveButton : "Sauvegarder",
		resetButton : "Réinitialiser",
		cancelButton : "Annuler",
		textAngle : 'Angle',
		fontName : 'Police',
		drawSampleRotatedText : 'angle',
		boldTitle : 'Gras',
		boldCharacter : 'B',
		italicTitle : 'Italique',
		italicCharacter : 'I',
		underlineTitle : 'Souligné',
		underlineCharacter : 'U',
		addMessage : 'Vous pouvez maintenant faire votre dessin sur la carte',
		editMessage : 'NB : vous pouvez modifier/déplacer la géométrie sur la carte',
		snappingMessage : 'NB : l\'accrochage est possible (utiliser la touche CTRL)',
		hideOption : 'Cacher les dessins',
		textPlacement : 'Placement',
		isMeasureMessage:'Cette étiquette est une mesure',
		west:'O',
		east:'E',
		north:'N',
		south:'S',
		arrow: 'Flèche',
		arrowNone: 'Non',
		arrowBegin: 'Début',
		arrowBeginEnd: 'Début et fin',
		arrowEnd: 'Fin'
	}));
