define({
	root : ({
		addDistance : "Add Length Unit",
		addArea : "Add Area Unit",
		addFontFamily : "Add a font family",
		label : "Label",
		value : "Value",
		abbr : "Abbreviation",
		conversion : "Conversion",
		actions : "Actions",
		areaUnits : "Area Units",
		distanceUnits : "Length Units",
		kilometers : "Kilometers",
		miles : "Miles",
		meters : "Meters",
		nauticals : "Nautical miles",
		feet : "Feet",
		yards : "Yards",
		squareKilometers : "Square kilometers",
		squareMiles : "Square miles",
		acres : "Acres",
		hectares : "Hectares",
		squareMeters : "Square meters",
		squareFeet : "Square feet",
		squareYards : "Square yards",
		distance : "Distances",
		area : "Areas",
		confirmOnDeleteLabel : "Ask for confirmation before deleting ?",
		listShowUpAndDownButtons : "Show up & down buttons in list?",
		allowLocalStorageLabel : "Use local storage ?",
		localStorageKeyLabel : "Local storage key",
		localStorageKeyInfo : "If not empty, applications with same key (and same server) will share the same storage. If empty, all will share same storage.",
		exportFileName : "Export file name",
		exportFileNameValue : "myDrawing.json",
		kilometersAbbreviation : "km",
		milesAbbreviation : "mi",
		metersAbbreviation : "m",
		nauticalsAbbreviation : "NM",
		feetAbbreviation : "ft",
		yardsAbbreviation : "yd",
		squareKilometersAbbreviation : "sq km",
		squareMilesAbbreviation : "sq mi",
		acresAbbreviation : "ac",
		hectaresAbbreviation : "ha",
		squareMetersAbbreviation : "sq m",
		squareFeetAbbreviation : "sq ft",
		squareYardsAbbreviation : "sq yd",
		defineUnits : "Define the measurement units.",
		operationalLayer : "Add the drawing as an operational layer of the map."
	}),
	"ar" : 1,
	"cs" : 1,
	"da" : 1,
	"de" : 1,
	"el" : 1,
	"es" : 1,
	"et" : 1,
	"fi" : 1,
	"fr" : 1,
	"he" : 1,
	"it" : 1,
	"ja" : 1,
	"ko" : 1,
	"lt" : 1,
	"lv" : 1,
	"nb" : 1,
	"nl" : 1,
	"pl" : 1,
	"pt-br" : 1,
	"pt-pt" : 1,
	"ro" : 1,
	"ru" : 1,
	"sv" : 1,
	"th" : 1,
	"tr" : 1,
	"vi" : 1,
	"zh-cn" : 1,
	"zh-hk" : 1,
	"zh-tw" : 1
});
