define(
    ({
        addDistance: "Ajouter une unité de longueur",
        addArea: "Ajouter une unité de surface",
        addFontFamily: "Ajouter une police de caractères",
        label: "Etiquette",
        value: "Valeur",
        abbr: "Abréviation",
        conversion: "Conversion",
        actions: "Actions",
        areaUnits: "Unités de surface",
        distanceUnits: "Unités de longueur",
        kilometers: "Kilomètres",
        miles: "Miles",
        meters: "Mètres",
        meters: "Mètres",
        nauticals: "Milles marins",
        feet: "Pieds",
        yards: "Yards",
        squareKilometers: "Kilomètres carrés",
        squareMiles: "Miles carrés",
        acres: "Acres",
        hectares: "Hectares",
        squareMeters: "Mètres carrés",
        squareFeet: "Pieds carrés",
        squareYards: "Yards carrés",
        distance: "Distances",
        area: "Surfaces",
        confirmOnDeleteLabel: "Demander confirmation à l'utilisateur avant une suppression",
        listShowUpAndDownButtons : "Montrer les bouttons haut/bas dans la liste ?",
        allowLocalStorageLabel: "Utiliser local storage",
        localStorageKeyLabel: "Clé Local storage",
        localStorageKeyInfo: "Si vide, toutes les applications partageront le même storage. Sinon, les applications avec la même clé partageront le même storage.",
        exportFileName: "Nom du fichier exporté",
        exportFileNameValue: "mesDessins.json",
		kilometersAbbreviation : "km",
		milesAbbreviation : "mi",
		metersAbbreviation : "m",
		nauticalsAbbreviation : "NM",
		feetAbbreviation : "ft",
		yardsAbbreviation : "yd",
		squareKilometersAbbreviation : "km²",
		squareMilesAbbreviation : "mi²",
		acresAbbreviation : "ac",
		hectaresAbbreviation : "ha",
		squareMetersAbbreviation : "m²",
		squareFeetAbbreviation : "ft²",
		squareYardsAbbreviation : "yd²",
		defineUnits : "Définir l'unité de mesure.",
		operationalLayer : "Ajouter le dessin comme couche opérationnelle de la carte."
    })
);