define({
	root : ({
		_widgetLabel : "Draw",
		yes:"Yes",
		yes:"Yes",
		no:"No",
		selectDrawMode : "Select drawing mode",
		clear : "Clear",
		point : "Point",
		line : "Line",
		polyline : "Polyline",
		freehandPolyline : "Freehand Polyline",
		triangle : "Triangle",
		extent : "Envelope",
		circle : "Circle",
		ellipse : "Ellipse",
		polygon : "Polygon",
		freehandPolygon : "Freehand Polygon",
		text : "Text",
		textWarningMessage : "Text must be written before placing the point on map",
		style : "Style",
		alpha : "Transparency",
		width : "Width",
		size : "Size",
		color : "Color",
		markerColor : "Marker Color",
		outlineColor : "Outline Color",
		lineColor : "Line Color",
		fillColor : "Fill Color",
		showMeasurements : "Show Measurements",
		areaUnits : "Area Units",
		distanceUnits : "Distance Units",
		pointUnits : "Point Units",
		pointUnits : "Units",
		unitMap : "Map Unit",
		unitDMS : "Degres Minutes Seconds Unit",
		unitDD : "Decimal Degres Unit",
		kilometers: "Kilometers",
		miles : "Miles",
		meters : "Meters",
		nauticals : "Nautical miles",
		feet : "Feet",
		yards : "Yards",
		squareKilometers : "Square kilometers",
		squareMiles : "Square miles",
		acres : "Acres",
		hectares : "Hectares",
		squareMeters : "Square meters",
		squareFeet : "Square feet",
		squareYards : "Square yards",
		confirmDrawDelete : "Delete this drawing ?",
		confirmDrawCheckedDelete : "Delete checked drawing ?",
		all : "All",
		draws : 'drawings',
		addDrawTitle : 'Add a drawing',
		editDrawTitle : 'Edit a drawing',
		listDrawTitle : 'Drawings list',
		importExportTitle : 'Import or export drawings',
		exportTitle : "Export draws",
		importTitle : "Import draws",
		importErrorMessageNavigator : "Your navigator doesn't support this functionnality.",
		importErrorWarningSelectFile : "Please select a file.",
		importDragAndDropMessage : "Select a file in input or drag and drop a file in this area.",
		importWarningNoDrawings : "No drawings to load",
		importErrorFileStructure : "The file structure doesn't match.",
		importWarningNoExport0Draw : "No export of the file (No drawing to export).",
		importCloseButton:"Close",
		nameField : "Name",
		symbolField : "Symbol",
		nameFieldDefaultValue : "My drawing",
		descriptionField : "Description",
		localLoading : "Your last drawings were loaded",
		editLabel : "Update this drawing",
		deleteLabel : "Delete this drawing",
		upLabel : "Move this drawing up",
		downLabel : "Move this drawing down",
		zoomLabel : "Zoom on this drawing",
		zoomAllLabel : "Zoom on selected drawings",
		copyLabel : "Copy selected drawings",
		copySuffix : " (copy)",
		deleteAllLabel : "Delete selected drawings",
		exportLabel : "Export selected drawings",
		noSelection : "No drawings selected",
		saveButton : "Save",
		resetButton : "Reset",
		cancelButton : "Cancel",
		textAngle : 'Text Angle',
		fontName : 'Font Name',
		drawSampleRotatedText : 'angle',
		boldTitle : 'Bold',
		boldCharacter : 'B',
		italicTitle : 'Italic',
		italicCharacter : 'I',
		underlineTitle : 'Underline',
		underlineCharacter : 'U',
		addMessage : 'You can now make your drawing on map',
		editMessage : 'NB : you can modify/move geometry on map',
		snappingMessage : 'NB : snapping is allowed (use CTRL)',
		hideOption : 'Hide drawings',
		textPlacement : 'Placement',
		isMeasureMessage:'This label is a measure',
		west:'W',
		east:'E',
		north:'N',
		south:'S'
	}),
	"ar" : 1,
	"cs" : 1,
	"da" : 1,
	"de" : 1,
	"es" : 1,
	"et" : 1,
	"fi" : 1,
	"fr" : 1,
	"he" : 1,
	"it" : 1,
	"ja" : 1,
	"ko" : 1,
	"lt" : 1,
	"lv" : 1,
	"nb" : 1,
	"nl" : 1,
	"pl" : 1,
	"pt-br" : 1,
	"pt-pt" : 1,
	"ro" : 1,
	"ru" : 1,
	"sv" : 1,
	"th" : 1,
	"tr" : 1,
	"vi" : 1,
	"zh-cn" : 1
});
