define({
    root: ({
        _widgetLabel: "Draw",
        selectDrawMode: "Select drawing mode",
        clear: "Clear",
        point: "Point",
        line: "Line",
        polyline: "Polyline",
        freehandPolyline: "Freehand Polyline",
        triangle: "Triangle",
        extent: "Envelope",
        circle: "Circle",
        ellipse: "Ellipse",
        polygon: "Polygon",
        freehandPolygon: "Freehand Polygon",
        text: "Text",
        textWarningMessage: "Text must be written before placing the point on map",
        style: "Style",
        alpha: "Transparency",
        width: "Width",
        size: "Size",
        color: "Color",
        markerColor: "Marker Color",
        outlineColor: "Outline Color",
        lineColor: "Line Color",
        fillColor: "Fill Color",
        showMeasurements: "Show Measurements",
        areaUnits: "Area Units",
        distanceUnits: "Distance Units",
        kilometers: "Kilometers",
        miles: "Miles",
        meters: "Meters",
        feet: "Feet",
        yards: "Yards",
        squareKilometers: "Square kilometers",
        squareMiles: "Square miles",
        acres: "Acres",
        hectares: "Hectares",
        squareMeters: "Square meters",
        squareFeet: "Square feet",
        squareYards: "Square yards",
        confirmDrawDelete: "This graphic will be deleted",
        all: "All",
        draws: 'graphics',
        addDrawTitle: 'Add a graphic',
        editDrawTitle: 'Edit a graphic',
        listDrawTitle: 'Graphics list',
        importExportTitle: 'Import or export drawing',
        exportTitle: "Export drawing",
        importTitle: "Import drawing",
        importErrorMessageNavigator: "Your navigator doesn't support this functionality.",
        importErrorWarningSelectFile: "Please select a file.",
        importWarningNoDrawings: "No drawing to load",
        importErrorFileStructure: "The file structure doesn't match.",
        importWarningNoExport0Draw: "No drawing to export.",
        nameField: "Name",
        symbolField: "Symbol",
        nameFieldDefaultValue: "My graphic",
        descriptionField: "Description",
        localLoading: "Your last drawing was loaded",
        editLabel: "Update this graphic",
        deleteLabel: "Delete this graphic",
        upLabel: "Move this graphic up",
        downLabel: "Move this graphic down",
        zoomLabel: "Zoom on this graphic",
        zoomAllLabel: "Zoom on all graphics",
        saveButton: "Save",
        resetButton: "Reset",
        cancelButton: "Cancel",
        textAngle: 'Text Angle',
        fontName: 'Font Name',
        drawSampleRotatedText: 'angle',
        boldTitle: 'Bold',
        boldCharacter: 'B',
        italicTitle: 'Italic',
        italicCharacter: 'I',
        underlineTitle: 'Underline',
        underlineCharacter: 'U',
        addMessage: 'You can now draw your graphic on the map',
        editMessage: 'NB : you can modify/move geometry on map',
        snappingMessage: 'NB : snapping is allowed (use CTRL)',
        hideOption: 'Hide graphics',
        textPlacement: 'Placement'
    }),
    "ar": 1,
    "cs": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fi": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lt": 1,
    "lv": 1,
    "nb": 1,
    "nl": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "th": 1,
    "tr": 1,
    "vi": 1,
    "zh-cn": 1
});